apiVersion: v1
kind: Service
metadata:
  name: ingress-service-devops
  namespace: haproxy-controller-devops
spec:
  type: NodePort
  selector:
    run: haproxy-ingress
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 32456
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    nodePort: 32567
    protocol: TCP
  - name: stat
    port: 1024
    targetPort: 1024
    nodePort: 32678
    protocol: TCP

